name: Build test

on:
  push:
    branches: {}
  pull_request:
    branches: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.3.0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.0
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Create .env.local
        run: |
          echo "NEXT_PUBLIC_SUPABASE_URL=${{ secrets.SUPABASE_PROJECT_URL }}" >> .env.local
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.SUPABASE_PROJECT_ANON_KEYS }}" >> .env.local

      - name: Build Test
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_PROJECT_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_PROJECT_API_KEYS }}
        run: pnpm build

      - name: Start Next.js Server (Optional)
        run: pnpm start &
